version: "3"

services:

  swimmy-db:
    container_name: swimmy-db
    image: postgres
    restart: on-failure
    env_file: .env
    volumes:
        - ./docker/postgresql/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
      
  swimmy-web:
    build: ./docker/fastapi/
    env_file: .env
    volumes:
      - ./docker/fastapi:/fastapi
    ports:
      - "80:8000"
    depends_on:
      - swimmy-db