"""update user model

Revision ID: 661aaef6999b
Revises: ada85970e5f9
Create Date: 2022-05-27 12:50:06.299089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661aaef6999b'
down_revision = 'ada85970e5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_user_id', table_name='user')
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_phone_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'is_instructor')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'is_administrator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_administrator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_instructor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
