"""Add user model

Revision ID: d8eba1e70902
Revises: d18a4417b11e
Create Date: 2022-05-27 17:18:54.806863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8eba1e70902'
down_revision = 'd18a4417b11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
