"""Test

Revision ID: 043d20254d53
Revises: c6eda13a36d5
Create Date: 2022-06-06 13:37:31.279554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043d20254d53'
down_revision = 'c6eda13a36d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups_members', sa.Column('member_sex', sa.String(), nullable=False))
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('groups_members', 'member_sex')
    # ### end Alembic commands ###
