"""Test

Revision ID: 1067702e05d0
Revises: c3e343b9ccc0
Create Date: 2022-06-02 12:39:52.475422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1067702e05d0'
down_revision = 'c3e343b9ccc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('sex', sa.String(), nullable=True))
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'sex')
    # ### end Alembic commands ###
