"""Add instructors workin hours

Revision ID: 16f0c6fa2467
Revises: 5d4585580722
Create Date: 2022-06-05 12:31:42.899754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f0c6fa2467'
down_revision = '5d4585580722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors_workigs_hours', sa.Column('min_hours', sa.Integer(), nullable=False))
    op.add_column('instructors_workigs_hours', sa.Column('max_hours', sa.Integer(), nullable=False))
    op.add_column('instructors_workigs_hours', sa.Column('preferred_start', sa.Time(), nullable=True))
    op.add_column('instructors_workigs_hours', sa.Column('preferred_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors_workigs_hours', 'preferred_end')
    op.drop_column('instructors_workigs_hours', 'preferred_start')
    op.drop_column('instructors_workigs_hours', 'max_hours')
    op.drop_column('instructors_workigs_hours', 'min_hours')
    # ### end Alembic commands ###
