"""Add instructors workin hours

Revision ID: 5d4585580722
Revises: b1aa3a840991
Create Date: 2022-06-05 12:26:59.975885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4585580722'
down_revision = 'b1aa3a840991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
