"""Test

Revision ID: 789ac31842e1
Revises: 16f0c6fa2467
Create Date: 2022-06-05 18:14:47.657936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789ac31842e1'
down_revision = '16f0c6fa2467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'free_places')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('free_places', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
