"""Test

Revision ID: 829fedb37b26
Revises: 1dde46cbf1d6
Create Date: 2022-06-02 19:05:36.810994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829fedb37b26'
down_revision = '1dde46cbf1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
