"""Test

Revision ID: a39b283a67b9
Revises: 356faf26ec6e
Create Date: 2022-06-01 18:09:27.500941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39b283a67b9'
down_revision = '356faf26ec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_name_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_role_name_fkey', 'users', 'roles', ['role_name'], ['name'])
    # ### end Alembic commands ###
