"""Test

Revision ID: f53b751d238b
Revises: 7606b4f63238
Create Date: 2022-06-02 12:04:24.996001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53b751d238b'
down_revision = '7606b4f63238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
